#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : docutils
Version  : 0.13.1
Release  : 23
URL      : http://pypi.debian.net/docutils/docutils-0.13.1.tar.gz
Source0  : http://pypi.debian.net/docutils/docutils-0.13.1.tar.gz
Summary  : Docutils -- Python Documentation Utilities
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GPL-2.0 Public-Domain Python-2.0
Requires: docutils-bin
Requires: docutils-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=======================
=======================
:Author: David Goodger
:Contact: goodger@python.org
:Date: $Date: 2014-07-07 04:36:36 +0200 (Mo, 07. Jul 2014) $
:Web site: http://docutils.sourceforge.net/

%package bin
Summary: bin components for the docutils package.
Group: Binaries

%description bin
bin components for the docutils package.


%package python
Summary: python components for the docutils package.
Group: Default

%description python
python components for the docutils package.


%prep
%setup -q -n docutils-0.13.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492372983
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd test ; ./alltests.py ; popd
%install
export SOURCE_DATE_EPOCH=1492372983
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rst2html.py
/usr/bin/rst2html5.py
/usr/bin/rst2latex.py
/usr/bin/rst2man.py
/usr/bin/rst2odt.py
/usr/bin/rst2odt_prepstyles.py
/usr/bin/rst2pseudoxml.py
/usr/bin/rst2s5.py
/usr/bin/rst2xetex.py
/usr/bin/rst2xml.py
/usr/bin/rstpep2html.py

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
